services:
  postgres:
    image: postgres:17.4
    ports:
      - '5433:5432'   # Host port 5433 mapped to container's 5432
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
